# Generated by Django 3.1.2 on 2020-10-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='SOMETHING STRONG', upload_to='images/'),
        ),
    ]
